dell/terraform-provider-redfish

redfish/data_source_redfish_bios.go
redfish/provider.go

Updated the Bios data source inline with latest provider design.
redfish_data_source_bios.go
**bios.tf**
```
provider "redfish" {
}
variable "rack1" {
}
data "redfish_bios" "bios" {
for_each = var.rack1
redfish_server {
user = each.value.user
password = each.value.password
endpoint = each.value.endpoint
ssl_insecure = each.value.ssl_insecure
}
}
output "bios_attributes" {
value = "${data.redfish_bios.bios}"
}
```
```paste below
$ terraform apply
data.redfish_bios.bios["my-server-2"]: Refreshing state...
data.redfish_bios.bios["my-server-1"]: Refreshing state...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
bios_attributes = {
"my-server-1" = {
"attributes" = {
"AcPwrRcvry" = "Last"
"AesNi" = "Enabled"
"AssetTag" = "" …
```

Updated Bios data source

---

docs/CONTRIBUTING.md
docs/PROVIDER.md
main.go
redfish/config.go

PROVIDER.md:
- Fixed minor grammatical errors (ex: an vs and, their vs there)
- Replaced mixtures of the infinitive/gerund/past participle
- Changed non-standard uses of passive voice
- Added missing articles
CONTRIBUTING.md:
- Added a section on how to set up a debugger using GoLand
- Added a pointer to the providers tutorial to help people get started
config.go:
- Fixed a type-o
main.go:
- Added the ability to put the provider in debug mode by changing a flag
Signed-off-by: Grant Curell <grant_curell@dell.com>

Documentation Update

---

redfish/resource_redfish_bios.go

Fixes #18
Signed-off-by: Virgil Chereches <virgil.chereches@gmail.com>
Closes #18
`redfish_bios`
The provider should wait until bios change job has finished and return a failure if the job fails.
The right way to implement this wait is by using TF SDK StateChangeConf method - other providers such as GCP and AWS ones are using this method whenever the provider should wait after some events during create/update of a resource.
```paste below
```
```release-note
```
```
...
```
* Please …

Add bios change job wait using StateChangeConf method

---

examples/bios/bios.tf
redfish/resource_redfish_bios.go

Added idempotency support for the redfish BIOS resource 
Closes #19 
redfish_resource_bios
**_After:_**
```paste below
$ terraform apply
redfish_bios.bios["my-server-2"]: Refreshing state... [id=/redfish/v1/Systems/System.Embedded.1/Bios]
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```
```release-note
Added idempotency support for redfish bios resource
```
```
...
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, …

issue_number #19: Added idempotency support for Bios

---

go.mod

- A version of gofish which fixes the service.Entity.Client.PostMultipartWithHeaders undefined bug is available
Signed-off-by: Grant Curell <grant_curell@dell.com>

go.mod: Rev gofish version

---

mutexkv/mutexkv.go
mutexkv/mutexkv_test.go
redfish/common.go
redfish/provider.go
redfish/resource_redfish_bios.go
redfish/resource_redfish_power.go
redfish/resource_redfish_simple_update.go
redfish/resource_redfish_storage_volume.go
redfish/resource_redfish_user_account.go
redfish/resource_redfish_virtual_media.go

Closes #40 
All resources
Every time a changing operation is done in a server, the resource in charge tries to acquire a lock that prevents other resources that want to perform changes in the same server to do so at the same time (race condition).
This Mutex must be used in all server changing operations, no matter if they restart the server or not. 
If an operation (like the delete ones) does not perform any changes and it only change the statefile (like getting rid of the ID), this lock must not be used.
The lock store will have as many locks as servers are being managed by the provider. 
The lock store is a map where the key is the server endpoint, while the value is a pointer to the server Mutex. 
Also, a new function has been created in the redfish package …

MutexKV implemented in all resources

---

go.mod

Closes #47
This PR updates gofish version from v0.10.0 to v0.11.0 to allow the provider start using the "plugin" system capabilities.

Dependency updated

---

examples/boot/boot.tf
examples/boot/terraform.tfvars
examples/boot/vars.tf
redfish/data_source_redfish_system_boot.go
redfish/provider.go

Added data source for Redfish ComputerSystem Boot resource
Relates #39 
data_source_redfish_system_boot
```paste below
$ terraform apply
Changes to Outputs:
+ system_boot = (sensitive value)
You can apply this plan to save these new output values to the Terraform state,
without changing any real infrastructure.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
Outputs:
system_boot = <sensitive>
```
**_terraform.tfstate_**
```
{
"version": 4,
"terraform_version": "1.0.2",
"serial": 2,
"lineage": "6372e915-e955-ce2f-a5d7-2f97ab2568c5",
"outputs": {
"system_boot": {
"value": {
"my-server-1": {
"boot_order": [ …
```

Added data source for Redfish ComputerSystem Boot resource

---

redfish/data_source_redfish_virtual_media_test.go

```
TF_ACC=1 go test $(go list ./... | grep -v 'vendor') -v -run=TestAccRedfishVirtualMedia_fetch -timeout 120m
?       github.com/dell/terraform-provider-redfish      [no test files]
?       github.com/dell/terraform-provider-redfish/common       [no test files]
testing: warning: no tests to run
PASS
ok      github.com/dell/terraform-provider-redfish/gofish/dell  0.006s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/dell/terraform-provider-redfish/mutexkv      0.012s [no tests to run]
=== RUN   TestAccRedfishVirtualMedia_fetch
--- PASS: TestAccRedfishVirtualMedia_fetch (11.01s)
PASS
ok      github.com/dell/terraform-provider-redfish/redfish      11.022s
```

Added acceptance test for virtual media datasource

---

redfish/data_source_redfish_system_boot_test.go

Added acceptance test for system boot datasource.

System boot datasource acceptance tests

---

redfish/resource_redfish_storage_volume.go

Minimum allowed capacity_byes is 1000000000 (1MB) for volume resource.

Validation added for min capacity_bytes

---

redfish/resource_redfish_storage_volume.go

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
~ update in-place
Terraform will perform the following actions:
~ resource "redfish_storage_volume" "volume" {
~ drives                = [
- "Solid State Disk 0:0:1",
- "",
]
id                    = "/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes/Disk.Virtual.0:RAID.Integrated.1-1"
}
Plan: 0 to add, 1 to change, 0 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: yes
redfish_storage_volume.volume["my-server-1"]: Modifying... [id=/redfish/v1/Systems/System.Embedded.1/Storage/RAID.Integrated.1-1/Volumes/Disk.Virtual.0:R …
```

Fixing drives validation

---

redfish/provider/resource_redfish_dell_idrac_attributes.go
redfish/provider/resource_redfish_virtual_media.go

1. Fixed bug with virtual media where server credentials were getting read from state instead of plan in update.
2. Fixed bug with iDRAC attributes resource where it didn't returned after error.

Fixing virtual media and idrac attributes resource

---

redfish/provider/resource_redfish_manager_reset.go

As manager reset doesn't need to perform any update operation because every time user wants to reset manager, it should perform reset action. So, added plan modifiers for id and reset type attributes and removed implementation for update(which was doing same thing as create).
```
=== RUN   TestAccRedfishManagerReset_Invalid_ResetType_Negative
--- PASS: TestAccRedfishManagerReset_Invalid_ResetType_Negative (0.20s)
=== RUN   TestAccRedfishManagerReset_Invalid_ManagerID_Negative
--- PASS: TestAccRedfishManagerReset_Invalid_ManagerID_Negative (7.28s)
=== RUN   TestAccRedfishManagerReset_Update_Negative
--- PASS: TestAccRedfishManagerReset_Update_Negative (225.17s)
=== RUN   TestAccRedfishManagerReset_Create
--- PASS: TestAccRedfishManagerReset_Create (221.86s)
PASS
```

Adding plan modifier for manager reset

---

redfish/provider/resource_redfish_storage_volume.go
redfish/provider/resource_redfish_storage_volume_test.go

```
=== RUN   TestAccRedfishStorageVolume_InvalidController
--- PASS: TestAccRedfishStorageVolume_InvalidController (2.92s)
=== RUN   TestAccRedfishStorageVolume_InvalidDrive
--- PASS: TestAccRedfishStorageVolume_InvalidDrive (4.24s)
=== RUN   TestAccRedfishStorageVolume_InvalidVolumeType
--- PASS: TestAccRedfishStorageVolume_InvalidVolumeType (4.86s)
=== RUN   TestAccRedfishStorageVolumeUpdate_basic
--- PASS: TestAccRedfishStorageVolumeUpdate_basic (434.45s)
=== RUN   TestAccRedfishStorageVolumeCreate_basic
--- PASS: TestAccRedfishStorageVolumeCreate_basic (274.10s)
=== RUN   TestAccRedfishStorageVolume_basic
--- PASS: TestAccRedfishStorageVolume_basic (272.45s)
=== RUN   TestAccRedfishStorageVolume_OnReset
--- PASS: TestAccRedfishStorageVolume_OnReset (469.34s)
PASS
```

Fix storage volume import test

---

docs/resources/boot_source_override.md
examples/resources/redfish_boot_source_override/provider.tf
redfish/provider/resource_redfish_boot_sources_override.go

Added reboot for every case.
```
=== RUN   TestAccRedfishBootSourceOverride_basic
--- PASS: TestAccRedfishBootSourceOverride_basic (532.36s)
=== RUN   TestAccRedfishBootSourceOverride_updated
--- PASS: TestAccRedfishBootSourceOverride_updated (595.16s)
PASS
```

boot source override updated

---

docs/data-sources/storage.md
redfish/models/storage.go
redfish/provider/data_source_redfish_storage.go

Tested via module that pdisk ids are returned
```
pdisk_fqdds  = [
"Disk.Bay.0:Enclosure.Internal.0-1:RAID.Integrated.1-1",
"Disk.Bay.1:Enclosure.Internal.0-1:RAID.Integrated.1-1",
"Disk.Bay.2:Enclosure.Internal.0-1:RAID.Integrated.1-1",
]
```

Adding drive_ids field to storage datasource 

---

docs/resources/storage_volume.md
examples/resources/redfish_storage_volume/provider.tf
examples/resources/redfish_storage_volume/resource.tf
redfish/models/storage_volume.go
redfish/provider/resource_redfish_storage_volume.go
redfish/provider/resource_redfish_storage_volume_test.go

- Add Support for RAID6 and RAID60.
- Add Support for Creating Virtual Disks on BOSS Storage Controllers
- Add Support for Encrypted Virtual Disks
Storage Volume Resource
```
- Add Support for RAID6 and RAID60.
- Add Support for BOSS Storage Controllers
- Add Support for Encrypted Virtual Disks
```
```
--- PASS: TestAccRedfishStorageVolume_Encrypted (277.19s)
PASS
ok      terraform-provider-redfish/redfish/provider     280.722s
```
* Please do not leave "+1" or other comments that do not add relevant new information or …

Storage Volume Enhancement

---

redfish/provider/resource_redfish_dell_system_attributes.go

Issue: Importing system attributes with specific attributes was importing all the attributes instead of the specified ones.
Testing:
```
redfish_dell_system_attributes.system: Importing from ID "{\"username\":\"root\",\"password\":\"calvin\",\"endpoint\":\"https://10.226.197.142\",\"ssl_insecure\":true,\"attributes\":[\"PCIeSlotLFM.3.MaxLFM\"]}"...
redfish_dell_system_attributes.system: Import prepared!
Prepared redfish_dell_system_attributes for import
redfish_dell_system_attributes.system: Refreshing state... [id=importId]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
```
{
"version": 4,
"terraform_version": "1.6.4",
"serial": 3,
"lineage": …
```

fixed system attributes import

---

.goreleaser.yml

Config is copied from https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/.goreleaser.yml#L20
Also, creating draft release is useless as they do not work well with present signing automation. Removed that.
```
root@lglap049:~/terraform-provider-redfish# goreleaser build --skip-validate --snapshot
• starting build...
• loading config file                              file=.goreleaser.yml
• loading environment variables
• getting and validating git state
• building...                                    commit=6824ac53a8c194c768c062482b6f65e568b86e8a latest tag=v1.1.0
• pipe skipped                                   reason=disabled during snapshot mode
• parsing tag
• setting defaults
• running before hooks
• running                                        hook=go …
```

Add windows to goreleaser config

---

.golangci.yaml
redfish/provider/common.go
redfish/provider/data_source_redfish_bios.go
redfish/provider/data_source_redfish_dell_idrac_attributes.go
redfish/provider/data_source_redfish_firmware_inventory.go
redfish/provider/data_source_redfish_storage.go
redfish/provider/data_source_redfish_system_boot.go
redfish/provider/data_source_redfish_virtual_media.go
redfish/provider/resource_certificate.go
redfish/provider/resource_redfish_bios.go
redfish/provider/resource_redfish_boot_order.go
redfish/provider/resource_redfish_boot_sources_override.go
redfish/provider/resource_redfish_dell_idrac_attributes.go
redfish/provider/resource_redfish_dell_lifecycle_controller_attributes.go
redfish/provider/resource_redfish_dell_system_attributes.go
redfish/provider/resource_redfish_idrac_firmware_update.go
redfish/provider/resource_redfish_manager_reset.go
redfish/provider/resource_redfish_power.go
redfish/provider/resource_redfish_scp_export.go
redfish/provider/resource_redfish_scp_import.go
redfish/provider/resource_redfish_simple_update.go
redfish/provider/resource_redfish_simple_update_test.go
redfish/provider/resource_redfish_storage_volume.go
redfish/provider/resource_redfish_user_account.go
redfish/provider/resource_redfish_user_account_password_test.go
redfish/provider/resource_redfish_virtual_media.go
redfish/provider/resource_user_account_password.go

```
open redfish_test.env: no such file or directory
=== RUN   TestAccRedfishBiosDataSource_basic
--- PASS: TestAccRedfishBiosDataSource_basic (13.00s)
=== RUN   TestAccRedfishiDRACDataSource_fetch
--- PASS: TestAccRedfishiDRACDataSource_fetch (10.47s)
=== RUN   TestAccRedfishFirmwareDataSource_basic
--- PASS: TestAccRedfishFirmwareDataSource_basic (86.05s)
=== RUN   TestAccRedfishStorageDataSource_fetch
--- PASS: TestAccRedfishStorageDataSource_fetch (58.88s)
=== RUN   TestAccRedfishSystemBoot_fetch
--- PASS: TestAccRedfishSystemBoot_fetch (14.17s)
=== RUN   TestAccRedfishSystemBoot_fetchInvalidID
--- PASS: TestAccRedfishSystemBoot_fetchInvalidID (1.56s)
=== RUN   TestAccRedfishVirtualMedia_fetch
--- PASS: TestAccRedfishVirtualMedia_fetch (11.37s)
=== RUN …
```

Session based auth

---

redfish/provider/resource_redfish_manager_reset.go
redfish/provider/resource_redfish_manager_reset_test.go
redfish/provider/resource_redfish_storage_volume_test.go

=== RUN   TestAccRedfishManagerReset_Invalid_ResetType_Negative
--- PASS: TestAccRedfishManagerReset_Invalid_ResetType_Negative (0.17s)
=== RUN   TestAccRedfishManagerReset_Invalid_ManagerID_Negative
--- PASS: TestAccRedfishManagerReset_Invalid_ManagerID_Negative (2.15s)
=== RUN   TestAccRedfishManagerReset_Update_Negative
--- PASS: TestAccRedfishManagerReset_Update_Negative (341.24s)
=== RUN   TestAccRedfishManagerReset_Create
--- PASS: TestAccRedfishManagerReset_Create (341.35s)
=== RUN   TestAccRedfishCertificate_basic
--- PASS: TestAccRedfishCertificate_basic (679.02s)

Session-based-auth changes added for remaining resources

---

redfish/provider/common.go
redfish/provider/data_source_redfish_system_boot_test.go
redfish/provider/resource_redfish_boot_order_test.go
redfish/provider/resource_redfish_boot_sources_override_test.go
redfish/provider/resource_redfish_storage_volume_test.go

```
open redfish_test.env: no such file or directory
=== RUN   TestAccRedfishBiosDataSource_basic
--- PASS: TestAccRedfishBiosDataSource_basic (12.44s)
=== RUN   TestAccRedfishiDRACDataSource_fetch
--- PASS: TestAccRedfishiDRACDataSource_fetch (11.50s)
=== RUN   TestAccRedfishFirmwareDataSource_basic
--- PASS: TestAccRedfishFirmwareDataSource_basic (77.46s)
=== RUN   TestAccRedfishNICDataSource_fetch
--- PASS: TestAccRedfishNICDataSource_fetch (177.66s)
=== RUN   TestAccRedfishStorageDataSource_fetch
--- PASS: TestAccRedfishStorageDataSource_fetch (56.87s)
=== RUN   TestAccRedfishSystemBoot_fetch
--- PASS: TestAccRedfishSystemBoot_fetch (24.47s)
=== RUN   TestAccRedfishSystemBoot_fetchInvalidID
--- PASS: TestAccRedfishSystemBoot_fetchInvalidID (1.41s)
=== RUN …
```

Acceptance tests fixed

---

redfish/provider/provider_test.go
redfish/provider/resource_redfish_nic_test.go

Add test cases to increase test coverage for nic resource.
Resource: redfish_network_adapter
redfish_network_adapter feature has four files:` resource_redfish_nic.go , resource_redfish_nic_helper.go, resource_redfish_nic_schema.go, resource_redfish_nic_schema_helper.go.`
If these four files are considered as a whole to calculate coverage,  the test coverage for the resource is ~85%.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not …

Add AT to increase NIC coverage.

---

docs/data-sources/system_boot.md
examples/data-sources/redfish_system_boot/data-source.tf
redfish/models/system_boot.go
redfish/provider/data_source_redfish_system_boot.go
redfish/provider/data_source_redfish_system_boot_test.go

Removal of resource_id in System Boot datasource
redfish_system_boot DATASOURCE
```paste below
```
```release-note
```
AT passed for redfish_system_boot:
```
...
```

Removal of resource_id in System Boot datasource

---

redfish/provider/common.go
redfish/provider/resource_redfish_storage_volume.go

TestAccRedfishStorageVolume_OnReset AT case always failed
Storage Volume resource
```paste below
```
```release-note
```
```
...
```

Bugfix for StorageVolume destroy with OnReset

---

redfish/provider/data_source_redfish_directory_service_auth_provider_certificate_test.go

adding certificateId var
```
...
```

adding certificateId var

---

redfish/provider/resource_redfish_storage_volume_test.go

Improved UT coverage for Storage Volume resource
Storage Volume resource
```paste below
```
```release-note
```
```
...
```

Storage volume resource UT fix

---

docs/resources/directory_service_auth_provider.md
examples/resources/redfish_directory_service_auth_provider/resource.tf
redfish/provider/data_source_redfish_directory_service_auth_provider.go
redfish/provider/resource_redfish_dell_lifecycle_controller_attributes.go
redfish/provider/resource_redfish_dell_lifecycle_controller_attributes_test.go
redfish/provider/resource_redfish_directory_service_auth_provider.go
redfish/provider/resource_redfish_directory_service_auth_provider_helper.go
redfish/provider/resource_redfish_directory_service_auth_provider_schema_helper.go
redfish/provider/resource_redfish_directory_service_auth_provider_test.go

Updating test coverage for DSAP and LC attributes
```
...
```

Updating test coverage for DSAP and LC attributes

---

redfish/provider/resource_redfish_user_account.go
redfish/provider/resource_redfish_user_account_test.go

Adding support for 17G in User account resource
```paste below
```
```release-note
```
16G AT:
17G AT:
16G UT:
17G UT:
```
...
```

Adding support for 17G in User account resource

---

docs/resources/storage_volume.md
examples/resources/redfish_storage_volume/resource.tf
redfish/provider/resource_redfish_simple_update.go
redfish/provider/resource_redfish_storage_volume.go
redfish/provider/resource_redfish_storage_volume_test.go

Storage volume resource 17G changes
Storage volume resource
```paste below
```
```release-note
```
```
...
```

Storage volume resource 17G changes

---

redfish/provider/resource_redfish_user_account_password.go
redfish/provider/resource_redfish_user_account_password_test.go

Adding Support for 17G in user account password resource
```paste below
```
```release-note
```
17G AT:
17G UT:
16G AT:
16G UT:
```
...
```

Adding Support for 17G in user account password resource

---

docs/resources/boot_source_override.md
docs/resources/dell_system_attributes.md
examples/resources/redfish_boot_source_override/resource.tf
examples/resources/redfish_dell_system_attributes/resource.tf
redfish/provider/resource_redfish_boot_sources_override.go
redfish/provider/resource_redfish_boot_sources_override_test.go

updating branching out for 17G boot source override
```
...
```

updating branching out for 17G boot source override
