- examples/bios/bios.tf
- examples/bios/main.tf
- redfish/provider.go
- redfish/resource_redfish_bios.go
Added BIOS resource provider for configuring the BIOS attributes:
- Create / Update - updates the BIOS attributes details. If a TaskMonitor/Job URI is returned in response header, then the ```bios_config_job_uri``` is updated with the TaskMonitor/Job URI. On subsequent apply, evaluate the ```bios_config_job_uri``` first. If the ```bios_config_job_uri``` contains a Job URI, then fetch the task status from the server BMC to determine whether the task is still running or has completed. If it is still running, then don't perform any configuration, else clear the ```bios_config_job_uri``` and patch the new attribute values.
- Destroy - clears the ID
```
provider "redfish" {
redfish_endpoint = "https://100.71.112.57"
user = "root"
password = "calvin"
ssl_insecure = true
}
resource …
```
> Added bios resource provider

- examples/bios/bios.tf
- examples/bios/main.tf
- examples/bios/terraform.tfvars
- examples/bios/vars.tf
- redfish/provider.go
- redfish/resource_redfish_bios.go
Update BIOS resource in line with provider design changes
resource_redfish_bios
**bios.tf**
```paste below
provider "redfish" {
//user = "root"
//password = "calvin"
}
variable "rack1" {
}
resource "redfish_bios" "bios" {
for_each = var.rack1
redfish_server {
user = each.value.user
password = each.value.password
endpoint = each.value.endpoint
ssl_insecure = each.value.ssl_insecure
}
attributes = {
"NumLock" = "On"
}
settings_apply_time = "OnReset"
}                                          
```
```
$ terraform apply
redfish_bios.bios["my-server-2"]: Refreshing state... [id=https://100.100.208.239/redfish/v1/Systems/System.Embedded.1/Bios]
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update …
```
> Update bios resource

- .gitignore
- examples/simple_update/resource/simpleUpdate.tf
- examples/simple_update/resource/terraform.tfvars
- examples/simple_update/resource/vars.tf
- redfish/provider.go
- redfish/resource_simple_update.go
This PR implements basic functionality for 
Closes #7 
redfish_simple_update
This resource adds basic functionality for simpleUpdate. At the moment only supports HTTP as *transfer_protocol*, but we are open to add more in the future as its needed. We stated for that one because it's the one dell implements in it's redfish implementation.
An example .tf file that could be used can be shown below:
```paste below
terraform {
required_providers {
redfish = {
source = "dell/redfish"
}
}
}
resource "redfish_simple_update" "update" {
for_each = var.rack1
redfish_server {
user = each.value.user
password = each.value.password
endpoint = each.value.endpoint
ssl_insecure = each.value.ssl_insecure
} 
transfer_protocol = "HTTP"
target_firmware_image = …
```
> SimpleUpdate resource implemented

- examples/firmware_inventory/firmware_inventory.tf
- examples/firmware_inventory/terraform.tfvars
- examples/firmware_inventory/vars.tf
- redfish/data_source_redfish_firmware_inventory.go
- redfish/provider.go
Created a data source for Firmware inventory which outputs all the "Installed" firmware details. The details included are Entity Name, Entity ID and Version. 
Relates  #7 
Firmware Inventory
The data source will be useful for users of this providers to capture the Firmware version on iDRAC before and after a Firmware Update for verification purpose.
```release-note
Data source for Firmware inventory to fetch currently install Firmware on iDRAC and its corresponding version number.
```
Test development in progress
* Please …
> Data source for Firmware inventory

- gofish/dell/common.go
- gofish/dell/common_test.go
- gofish/dell/dellAttributes.go
- gofish/dell/dellAttributes_test.go
- gofish/dell/manager.go
- gofish/dell/manager_test.go
- gofish/dell/updateService.go
- gofish/dell/updateService_test.go
This pull request wraps gofish UpdateService and Manager to parse and store Dell OEM data.
This will become handy when writing resources using OEM actions within this provider.
```release-note
Added 8 files:
gofish/dell/common_test.go
gofish/dell/common.go
gofish/dell/dellAttributes_test.go
gofish/dell/dellAttributes.go
gofish/dell/manager_test.go
gofish/dell/manager.go
gofish/dell/updateService_test.go
gofish/dell/updateService.go
```
* Please do not leave "+1" or other comments that do not add relevant new information or …
> Dell gofish UpdateService and Manager

- redfish/provider.go
- redfish/resource_redfish_simple_update.go
- redfish/resource_redfish_storage_volume.go
- redfish/resource_redfish_user_account.go
- redfish/resource_redfish_virtual_media.go
Closes #41
- redfish_user_account
- redfish_storage_volume
- redfish_virtual_media
- redfish_simple_update
Some non compliant filenames and signature functions have been change to compliant provider naming convention (added redfish keywork to both files and function signatures).
> Changed non compliant filenames and func signatures

- examples/idrac_attributes/data_source/idrac.tf
- examples/idrac_attributes/data_source/terraform.tfvars
- examples/idrac_attributes/data_source/vars.tf
- examples/idrac_attributes/resource/idrac.tf
- examples/idrac_attributes/resource/terraform.tfvars
- examples/idrac_attributes/resource/vars.tf
- gofish/dell/common_test.go
- gofish/dell/dellAttributeRegistry.go
- gofish/dell/dellAttributeRegistry_test.go
- redfish/data_source_redfish_dell_idrac_attributes.go
- redfish/provider.go
- redfish/resource_redfish_dell_idrac_attributes.go
Closes #14 
- redfish_dell_idrac_attributes resource
- redfish_dell_idrac_attributes datasource
```paste below
This PR brings a new resource for changing iDRAC attributes as well as a datasource for reading all possible values.
```
```release-note
- Added extended gofish structs for Dell Attribute registry
- Added support for iDRAC attributes resource and datasource
```
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers …
> idrac attributes datasource and resource implemented

- redfish/data_source_redfish_bios_test.go
Added test cases for bios DataSource
> Added test case for bios data source test

- redfish/data_source_redfish_firmware_inventory_test.go
> firmware inventory datasource test added

- redfish/resource_redfish_user_account.go
- redfish/resource_redfish_user_account_test.go
Changes added for user management
- user_id is added as an optional field to create a user
- Validations added 
- Acceptance test added
> User Management Resource Updated and Acceptance tests Added

- redfish/data_source_redfish_storage_test.go
> Storage volume datasource acceptance tests added

- redfish/resource_redfish_dell_idrac_attributes.go
- redfish/resource_redfish_dell_idrac_attributes_test.go
- Added read for state update after create/update resource.
- Updated idrac search based on substring match instead of matching hard coded idrac ID.
- Added acceptance tests
> Updated iDRAC attributes resource

- redfish/common.go
- redfish/resource_redfish_power.go
- redfish/resource_redfish_power_test.go
Nmi and PushButtonOption Added for Power Operation
Acceptance test Updated
Some code for power operation is present in common.go, so covered that.
In power.go most part is covered except system-related issues which the acceptance test cannot cover.
> Power Operation updated

- redfish/resource_redfish_bios.go
- redfish/resource_redfish_bios_test.go
Acceptance test added for bios resource
> Bios acceptance test added

- examples/idrac_attributes/resource/idrac.tf
- redfish/resource_redfish_dell_idrac_attributes_test.go
Updated iDRAC resource examples and minor change in acceptance test endpoint URL.
> iDRAC attributes resource example change

- redfish/resource_redfish_simple_update.go
- redfish/resource_redfish_simple_update_test.go
- Simple update now supports HTTP link along with local file path
- Acceptance test added
> Simple Update changes added

- examples/users/users.tf
- redfish/resource_redfish_user_account.go
validation added for username, password and user id
> User-resource bug fix

- redfish/resource_redfish_simple_update.go
- redfish/resource_redfish_simple_update_test.go
> NFS support added in simple update

- redfish/resource_redfish_storage_volume.go
Added validation for volume_name and drives of storage volume resource.
> Added validation for volume_name and drives

- redfish/resource_redfish_virtual_media.go
Added image extension validation while creating/updating virtual media.
> Virtual media image validation

- redfish/common.go
- redfish/resource_redfish_simple_update.go
- redfish/resource_redfish_user_account.go
> Simple update bugfix

- .github/SECURITY.md
- README.md
- about/CODE_OF_CONDUCT.md
- about/COMMITTER_GUIDE.md
- about/CONTRIBUTING.md
- about/INSTALLATION.md
- about/SUPPORT.md
Redfish 1.0.0 release activities
> Release activities

- GNUmakefile
- redfish/provider/resource_redfish_storage_volume.go
Also some minor changes in error messages.
Without this fix, any operation on storage volume is stalled forever.
> Fix: Modifying storage volume resource to use WaitForTask function

- redfish/provider/resource_certificate.go
```paste below
```
```release-note
```
```
...
```
> cert str len fix

- docs/resources/boot_order.md
- docs/resources/boot_source_override.md
- redfish/provider/resource_redfish_boot_order.go
- redfish/provider/resource_redfish_boot_sources_override.go
- templates/resources/boot_order.md.tmpl
- templates/resources/boot_source_override.md.tmpl
doc updates for boot order resource
> Boot Order doc updated

- docs/resources/certificate.md
- templates/resources/certificate.md.tmpl
Certificate Resource added notes for ssl certificate content.
```paste below
```
```release-note
```
```
...
```
> added certificate notes

- redfish/provider/common.go
- redfish/provider/resource_certificate.go
- redfish/provider/resource_redfish_manager_reset.go
Added additional step to perform API call while checking server/iDRAC status.
> Enhanced checkServerStatus

- .golangci.yaml
- GNUmakefile
- main.go
- redfish/provider/data_source_redfish_bios_test.go
- redfish/provider/data_source_redfish_dell_idrac_attributes_test.go
- redfish/provider/data_source_redfish_storage_test.go
- redfish/provider/data_source_redfish_virtual_media_test.go
- redfish/provider/provider_test.go
- redfish/provider/resource_redfish_boot_order_test.go
- redfish/provider/resource_redfish_simple_update.go
- redfish/provider/resource_redfish_storage_volume_test.go
- redfish/provider/resource_redfish_virtual_media_test.go
```paste below
```
```release-note
```
```
...
```
> PR Build Job 

- docs/resources/bios.md
- examples/resources/redfish_bios/import.sh
- redfish/provider/provider_test.go
- redfish/provider/resource_redfish_bios.go
- redfish/provider/resource_redfish_bios_test.go
- templates/resources/bios.md.tmpl
```
=== RUN   TestAccRedfishBios_Import
--- PASS: TestAccRedfishBios_Import (2.21s)
PASS
```
> bios resource import

- docs/resources/dell_idrac_attributes.md
- examples/resources/redfish_dell_idrac_attributes/import.sh
- redfish/provider/resource_redfish_dell_idrac_attributes.go
- redfish/provider/resource_redfish_dell_idrac_attributes_test.go
- templates/resources/dell_idrac_attributes.md.tmpl
import idrac attributes 
IDRAC Attributes Import 
> import idrac attributes

- redfish/provider/resource_redfish_dell_lifecycle_controller_attributes.go
1. Fixed attributes not found issue on iDRAC 7.x
2. Handled case where API query returns status code as success(200) along with extended error message in the body.
> LC attributes bug fix

- docs/resources/bios.md
- docs/resources/boot_order.md
- docs/resources/boot_source_override.md
- docs/resources/certificate.md
- docs/resources/simple_update.md
- docs/resources/virtual_media.md
- examples/resources/redfish_bios/resource.tf
- examples/resources/redfish_boot_order/resource.tf
- examples/resources/redfish_boot_source_override/resource.tf
- examples/resources/redfish_certificate/resource.tf
- examples/resources/redfish_simple_update/resource.tf
- examples/resources/redfish_virtual_media/resource.tf
```paste below
```
```release-note
```
```
...
```
> added possible value

- docs/resources/storage_volume.md
- examples/resources/redfish_storage_volume/resource.tf
- redfish/provider/resource_redfish_storage_volume.go
Update Encrypted Storage Volume Docs
Storage Volume Resource
> Update Encrypted Storage Volume Docs

- redfish/provider/resource_redfish_dell_idrac_attributes.go
- redfish/provider/resource_redfish_dell_lifecycle_controller_attributes.go
- redfish/provider/resource_redfish_dell_system_attributes.go
Valid iDRAC attributes:
```
redfish_dell_idrac_attributes.idrac: Importing from ID "{\"username\":\"root\",\"password\":\"calvin\",\"endpoint\":\"https://10.226.197.142\",\"ssl_insecure\":true, \"attributes\":[\"Users.3.Enable\", \"Time.1.Timezone\"]}"...
redfish_dell_idrac_attributes.idrac: Import prepared!
Prepared redfish_dell_idrac_attributes for import
redfish_dell_idrac_attributes.idrac: Refreshing state... [id=importId]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Invalid iDRAC attributes:
```
redfish_dell_idrac_attributes.idrac: Importing from ID "{\"username\":\"root\",\"password\":\"calvin\",\"endpoint\":\"https://10.226.197.142\",\"ssl_insecure\":true, …
```
> Added validation for iDRAC attributes import

- redfish/provider/resource_redfish_user_account_password_test.go
- redfish/provider/resource_user_account_password.go
> acceptance test added for user password update resource

- docs/resources/user_account_password.md
- examples/resources/redfish_user_account_password/resource.tf
- redfish/models/UserAccountPassword.go
- redfish/provider/resource_redfish_user_account_password_test.go
- redfish/provider/resource_user_account_password.go
> Naming convention update, pass changed to password

- docs/resources/idrac_server_configuration_profile_export.md
- docs/resources/idrac_server_configuration_profile_import.md
- examples/resources/redfish_idrac_server_configuration_profile_export/resource.tf
- examples/resources/redfish_idrac_server_configuration_profile_export/variables.tf
- examples/resources/redfish_idrac_server_configuration_profile_import/resource.tf
- examples/resources/redfish_idrac_server_configuration_profile_import/variables.tf
```paste below
```
```release-note
```
```
...
```
> server configuration profile example update

- docs/resources/user_account.md
- docs/resources/user_account_password.md
- templates/resources/user_account.md.tmpl
- templates/resources/user_account_password.md.tmpl
Added notes for user and user account password resource
> user doc updated

- gofish/dell/manager.go
- redfish/models/server_configuration_profile.go
- redfish/provider/resource_redfish_scp_export.go
- redfish/provider/resource_redfish_scp_import.go
```paste below
```
```release-note
```
```
...
```
> fix for FW v5 support

- about/ATTRIBUTION.md
- redfish/provider/resource_redfish_boot_sources_override.go
- redfish/provider/resource_redfish_power.go
- redfish/provider/resource_redfish_simple_update.go
- redfish/provider/resource_redfish_virtual_media.go
```paste below
```
```release-note
```
```
...
```
> Attribution

- docs/data-sources/system_boot.md
- redfish/models/system_boot.go
- redfish/provider/data_source_redfish_system_boot.go
- redfish/provider/data_source_redfish_system_boot_test.go
```paste below
```
```release-note
```
```
...
```
> added system_id to boot datasource and deprecated resource_id

- docs/data-sources/bios.md
- docs/data-sources/storage.md
- docs/resources/bios.md
- docs/resources/boot_order.md
- docs/resources/boot_source_override.md
- docs/resources/idrac_firmware_update.md
- docs/resources/power.md
- docs/resources/simple_update.md
- docs/resources/storage_volume.md
- docs/resources/virtual_media.md
- examples/data-sources/redfish_bios/data-source.tf
- examples/data-sources/redfish_storage/data-source.tf
- examples/resources/redfish_bios/resource.tf
- examples/resources/redfish_boot_order/resource.tf
- examples/resources/redfish_boot_source_override/resource.tf
- examples/resources/redfish_idrac_firmware_update/resource.tf
- examples/resources/redfish_power/resource.tf
- examples/resources/redfish_simple_update/resource.tf
- examples/resources/redfish_storage_volume/resource.tf
- examples/resources/redfish_virtual_media/resource.tf
```paste below
```
```release-note
```
```
...
```
> added system_id example

- redfish/provider/provider.go
- redfish/provider/resource_redfish_user_account.go
- redfish/provider/resource_redfish_user_account_test.go
Add invalidation function for password enhancement
We need to add one invalidation function to improvement customer experience:
When password is changed by user resource by  `terraform apply` , other resources in the tf configuration should be passed in this `terraform apply` action, not impacted by this password changing.
```paste below
```
```release-note
```
New at case for password enhancement is passed:
* Please do not leave "+1" or other comments that …
> Add invalidation function for password enhancement

- examples/README.md
Add ReadMe to example.
```paste below
```
```release-note
```
```
...
```
> Add ReadMe to example.

- docs/data-sources/directory_service_auth_provider.md
- redfish/models/directory_service_auth_provider.go
- redfish/provider/data_source_redfish_directory_service_auth_provider.go
updating datacenter license based update and removed kerberos key tab
```
...
```
> updating datacenter license based update and removed kerberos key tab

- .github/workflows/terraform-ci.yml
Error: running "terraform": exec: "terraform": executable file not found in $PATH
Solution: remove `go:generate terraform fmt -recursive ./examples/` from main.go
```paste below
```
```release-note
```
```
...
```
> Fix Generate Action Issue

- redfish/provider/resource_certificate.go
Enable password enhancement for certificate resource
```paste below
```
```release-note
```
```
...
```
> Enable password enhancement for certificate resource

- docs/resources/storage_controller.md
- examples/resources/redfish_storage_controller/resource.tf
- redfish/provider/resource_redfish_storage_controller.go
- redfish/provider/resource_redfish_storage_controller_schema.go
- redfish/provider/resource_redfish_storage_controller_schema_helper.go
- redfish/provider/resource_redfish_storage_controller_test.go
Storage controller resource code changes for apply time, maintenance window, documentation updates.
storage controller resource
```paste below
```
```release-note
```
```
...
```
> Storage controller resource maintenance apply time related changes

- redfish/provider/resource_redfish_manager_reset.go
Enable password enhancement for manager reset resource
Manager Reset Resource
```release-note
```
```
...
```
> Enable password enhancement for manager reset resource

- redfish/provider/provider_test.go
- redfish/provider/resource_redfish_directory_service_auth_provider_test.go
- redfish/provider/resource_redfish_user_account_test.go
- redfish/provider/resource_redfish_virtual_media_test.go
Adjust redfish params for AT cases.
```paste below
```
```release-note
```
```
...
```
> Fix AT failures

- redfish/provider/provider_test.go
Rename redfish_test.env to redfish.env
```paste below
```
```release-note
```
```
...
```
> Rename redfish_test.env to redfish.env

- gofish/dell/common_test.go
- redfish/provider/common.go
- redfish/provider/data_source_redfish_virtual_media.go
- redfish/provider/provider.go
- redfish/provider/resource_redfish_user_account_test.go
- redfish/provider/resource_redfish_virtual_media.go
fix checkmarx issues
- 
```paste below
```
```release-note
```
```
...
```
> fix checkmarx issues

- go.mod
- go.sum
- redfish/helper/redfish_dell_idrac_attributes.go
- redfish/provider/data_source_redfish_dell_idrac_attributes.go
- redfish/provider/data_source_redfish_directory_service_auth_provider.go
- redfish/provider/data_source_redfish_directory_service_auth_provider_certificate.go
- redfish/provider/data_source_redfish_nic.go
- redfish/provider/resource_redfish_dell_idrac_attributes_test.go
Improved Test UT and FT Coverage for data_source_redfish_dell_idrac_attributes file
data_source_redfish_dell_idrac_attribute
resource_redfish_dell_idrac_attribute
None
...
DataSource Test Results:
Resource Test Results:
Resource Coverage:
DataSource Coverage:
> Improved the UT coverage for data_source_redfish_dell_idrac_attributes

- docs/data-sources/directory_service_auth_provider_certificate.md
- docs/resources/directory_service_auth_provider_certificate.md
- examples/data-sources/redfish_directory_service_auth_provider_certificate/data-source.tf
- examples/resources/redfish_directory_service_auth_provider_certificate/resource.tf
- redfish/models/directory_service_auth_provider_certificate.go
- redfish/provider/data_source_redfish_directory_service_auth_provider_certificate.go
- redfish/provider/resource_redfish_directory_service_auth_provider_certificate.go
- redfish/provider/resource_redfish_directory_service_auth_provider_certificate_test.go
removing RSA 2FA Config and update testcase
```release-note
```
```
...
```
> removing RSA 2FA Config and update testcase

- redfish/provider/resource_redfish_bios_test.go
- redfish/provider/resource_redfish_storage_controller_test.go
- redfish/provider/resource_redfish_user_account_password_test.go
- redfish/provider/resource_user_account_password.go
Bios, Storage Controller, User Account Password resources UT fix
Bios, Storage Controller, User Account Password resources
```paste below
```
```release-note
```
```
...
```
> Bios, Storage Controller, User Account Password resources UT fix

- redfish/helper/redfish_virtual_media.go
- redfish/provider/resource_redfish_virtual_media.go
- redfish/provider/resource_redfish_virtual_media_test.go
UT coverage for Virtual media 
```release-note
```
```
...
```
> UT improvement for Virtual media

- redfish/provider/resource_redfish_nic_test.go
UT coverage improvement for NIC resource
```
...
```
> UT coverage improvement for NIC resource

- .github/CODEOWNERS
```paste below
```
```release-note
```
```
...
```
> Update code owners for RedFish provider

- redfish/provider/common.go
- redfish/provider/constants.go
- redfish/provider/data_source_redfish_virtual_media.go
17G branching out for Virtual Media Datasource
Virtual Media Datasource
```paste below
```
```release-note
```
```
...
```
> Implement 17G branching out for Virtual Media Datasource

- redfish/provider/data_source_redfish_nic_test.go
- redfish/provider/resource_redfish_dell_idrac_attributes.go
- redfish/provider/resource_redfish_dell_idrac_attributes_test.go
- redfish/provider/resource_redfish_manager_reset.go
Branching changes for idrac attribute resource, e-tag changes for manager reset and test changes for nic datasource
```paste below
```
```release-note
```
```
...
```
Screenshots:
**UT<17G:**
**UT=17G:**
**AT=17G**
**AT<17G**
> Branching changes for idrac attribute resource, e-tag changes for manager reset and test changes for nic datasource

- docs/resources/directory_service_auth_provider.md
- examples/resources/redfish_directory_service_auth_provider/resource.tf
- redfish/provider/resource_redfish_directory_service_auth_provider.go
- redfish/provider/resource_redfish_directory_service_auth_provider_helper.go
- redfish/provider/resource_redfish_directory_service_auth_provider_schema_helper.go
- redfish/provider/resource_redfish_directory_service_auth_provider_test.go
> 17G branching for DSAP

- redfish/provider/resource_redfish_simple_update.go
Simple update resource 17G changes
Simple update resource
```paste below
```
```release-note
```
```
...
```
> Simple update resource 17G changes

- redfish/helper/redfish_idrac_firmware_update.go
- redfish/provider/provider_test.go
- redfish/provider/resource_redfish_idrac_firmware_update.go
- redfish/provider/resource_redfish_idrac_firmware_update_test.go
Idrac firmware update defect fix
Idrac firmware update
```paste below
```
```release-note
```
```
...
```
> Idrac firmware update defect fix

- gofish/dell/computerSystem.go
- redfish/provider/resource_redfish_boot_order.go
- redfish/provider/resource_redfish_boot_order_test.go
- redfish/provider/resource_redfish_scp_export.go
- redfish/provider/resource_redfish_scp_import.go
17G Branching out for Boot Order and update for SCP tsak URI
```
...
```
> 17 g branching boot order

- gofish/dell/computerSystem.go
- gofish/dell/networkPort.go
rawData update for gofish update 
```
...
```
> updating rawData fix

- redfish/provider/resource_redfish_dell_system_attributes.go
- redfish/provider/resource_redfish_dell_system_attributes_test.go
Adding fix for PSPFCEnabled in dell system attribute resource
```paste below
```
```release-note
```
```
...
```
> Adding fix for PSPFCEnabled in dell system attribute resource

- redfish/provider/resource_redfish_scp_test.go
> need to update mock data for scp local share, hence commenting out

- redfish/provider/resource_redfish_storage_controller_test.go
Storage controller resource UT changes
Storage controller resource
```paste below
```
```release-note
```
```
...
```
> Storage controller resource UT changes

- common/job_management.go
- redfish/provider/resource_redfish_scp_test.go
updated mock data for scp local and removing commented code 
> updated mock data for scp local so uncommeting commented code

- redfish/helper/redfish_dell_idrac_attributes.go
Copyright check changes
dell idrac attributes
```paste below
```
```release-note
```
```
...
```
> Copyright check changes

- docs/resources/dell_idrac_attributes.md
- docs/resources/directory_service_auth_provider.md
- examples/resources/redfish_dell_idrac_attributes/resource.tf
- examples/resources/redfish_directory_service_auth_provider/resource.tf
docs update for DSAP and idrac dell attribute
```release-note
```
```
...
```
> updating doc and example for DSAP and iDRAC Dell attributes

- docs/resources/dell_idrac_attributes.md
- examples/resources/redfish_dell_idrac_attributes/provider.tf
- examples/resources/redfish_dell_idrac_attributes/terraform.tfvars
```paste below
```
```release-note
```
```
...
```
> Copyright Year Changes
